---
title: "Untitled"
output: html_document
---


```{r}
corps <- c("en_US.blogs.", "en_US.news.", "en_US.twitter.") 
```


Split data set in to 10% random blocks

```{r}
set.seed(1025)
twitter_groups <- sample(1:10, size = length(twitter),replace = TRUE)
news_groups <- sample(1:10, size = length(news),replace = TRUE)
blogs_groups <- sample(1:10, size = length(blogs),replace = TRUE)

twitter_splits <- lapply(1:10, function(n) twitter[twitter_groups == n])
blogs_splits <- lapply(1:10, function(n) blogs[blogs_groups == n])
news_splits <- lapply(1:10, function(n) news[news_groups == n])

rm(twitter_groups,news_groups,blogs_groups)

for (i in 1:10) {
  groups <- ceiling(length(twitter_splits[[i]])/20000)
  group_split <- sample(1:groups, length(twitter_splits[[i]]), replace = TRUE)
  split_corpus <- lapply(1:groups, function(n) twitter_splits[[i]][group_split == n])
  y <- apply_ngram(split_corpus, 3, wordFreq = 2)
  x <- paste("twitter_temp_",i, sep="")
  assign(x, y)
}

rm(list=ls(pattern="temp"))

```


```{r}
  groups <- ceiling(length(twitter_splits[[1]])/20000)
  group_split <- sample(1:groups, length(twitter_splits[[1]]), replace = TRUE)
  split_corpus <- lapply(1:groups, function(n) twitter_splits[[1]][group_split == n])
  y <- apply_ngram(split_corpus, 3, wordFreq = 2)
  x <- paste("twitter_temp_",1, sep="")
  assign(x, y)
```



```{r}

groups <- ceiling(length(sub_corpus)/20000)

group_split <- sample(1:groups, length(sub_corpus), replace = TRUE)

split_corpus <- lapply(1:groups, function(n) sub_corpus[group_split == n])

```

```{r}
apply_ngram <- function(split_corpus, Ngram, wordFreq = 20) {

z2 <- lapply(split_corpus, function(n) { 
  data.frame(table(NGramTokenizer(n, 
                   Weka_control(min = Ngram, max = Ngram, delimiters = " \\r\\n\\t.,;:\"()?!")
                   )
        ),
       stringsAsFactors = FALSE )
        }
  )

xx <- do.call(rbind.data.frame, z2)

xx <- group_by(xx, Var1)
xx <- summarise(xx, Freq = sum(Freq))%>%
  filter( Freq > wordFreq) %>%
  ungroup %>%
  arrange(-Freq)}


Ngram4 <- apply_ngram(split_corpus, 4)
Ngram3 <- apply_ngram(split_corpus, 3)
Ngram2 <- apply_ngram(split_corpus, 2)
Ngram1 <- apply_ngram(split_corpus, 1)



ngram_probs <- lapply(2:4, function(n) Ngram_probs(
  eval(parse(text = paste("Ngram",n, sep=""))), 
  eval(parse(text = paste("Ngram",n-1, sep=""))), 2))

Ngram2_probs <- Ngram_probs(Ngram2, Ngram1, 20)


pattern <- "and a case of"

wordcount <- if(length(ngram_probs) < str_count(pattern, "\\S+")) {
  length(ngram_probs)
  } else  {str_count(pattern, "\\S+")}

forNgrams <- sapply(1:wordcount, function(n) word(pattern, -n, -1))

results <-lapply(1:wordcount, function(n) filter(ngram_probs[[n]], predictor == forNgrams[[n]]))
results <- do.call(rbind.data.frame, results)
results <- ungroup(results) %>%
  arrange( desc(Prob), desc(Ngrams))
```
