---
title: "Untitled"
author: "Jonathan Bourne"
date: "Monday, December 08, 2014"
output: html_document
---

```{r}
library(reshape2)
```



Function to replace words with "[blank]" where required.
```{r}
insert_blank <- function(x , words, row = 1){

  t <- lapply(1:Ngram_case, function(n) {
  if(words[row,n] =="[blank]"){rep("[blank]", nrow(x) )} else{word(x$predictor, n)}
  })

x$predictor <- do.call(paste, t)
x$pattern <- paste(x$predictor ,x$dependent)

x <- group_by(x, pattern)
x <- summarise(x, predictor = predictor, 
               Freq = sum(Freq), 
               Ngrams = Ngram_case - sum(grepl("[blank]",words[row,]))+1, 
               dependent = dependent)%>%
      ungroup  %>%
      arrange(-Freq)

x <- group_by(x, predictor ) %>%
      mutate( Prob = Freq/sum(Freq)) %>%
      filter(min_rank(desc(Prob)) == 1) }
```

function that shows how data can be reduced compressed for a given loss of information
```{r}
reducer <- function(Ngram, max_cut_off = 50) {
 
  reduce <- sapply(1:max_cut_off, function(n){
  Ngram2 <-Ngram[Ngram$Freq >=n,]
  c(n,nrow(Ngram2)/nrow(Ngram),sum(Ngram2$Freq)/sum(Ngram$Freq))
})  
reduce <- data.frame(t(reduce)) 
names(reduce) <- c("cut_off","length_reduction", "Loss_of_information")  
reduce <-melt(data = reduce, id.vars ="cut_off")
}
```



```{r}

words <- data.frame(one = rep("x1",8), two = rep(c("x2","[blank]"), 1, each = 4), three = rep(c("x3","[blank]"), 2, each = 2), four = rep(c("x4","[blank]"), 4), stringsAsFactors = FALSE)

Ngram4 <- ngram_probs[[3]]
Ngram_case <- mean(Ngram4$Ngrams)-1
words2 <- words[!duplicated(words[,1:Ngram_case]),1:Ngram_case]
Ngram4_blank <- insert_blank(Ngram4, words2, 4)
Ngram4_blank$predictor <- word(Ngram4_blank$predictor, 1) 
Ngram4_blank$Ngrams <- 2.5

Ngram3 <- ngram_probs[[2]]
Ngram_case <- mean(Ngram3$Ngrams)-1
words2 <- words[!duplicated(words[,1:Ngram_case]),1:Ngram_case]
Ngram3_blank <- insert_blank(Ngram3, words2, 2)
Ngram3_blank$predictor <- word(Ngram3_blank$predictor, 1)
Ngram3_blank$Ngrams <- 1.5

ngram_probs_blank <- list(if_in_doubt,Ngram3_blank, Ngram4_blank)
save(ngram_probs_blank, file = "ngram_probs_blank.Rda")

reduce <- reducer(Ngram3_blank)
reduce2 <- reducer(Ngram4_blank)

ggplot(reduce2, aes( x= cut_off, y = value, colour = variable)) + geom_line()

blanks <- as.list(Ngram3_blank, Ngram4_blank)
```


```{r}
reduce3 <- lapply(x3, function(x){
  reduce <- sapply(1:30, function(n){
  x2 <-x[x$Freq >=n,]
  c(n,nrow(x2)/nrow(x),sum(x2$Freq)/sum(x$Freq))
})

data.frame(t(reduce))
})

red <- rbind_all(reduce3)

red <- cbind( red, rep(c(2,3,4,5), each = 30))
names(red) <- c("cut_off","length_reduction", "Loss_of_information", "Ngram")
red <-melt(data = red, id.vars =c("cut_off", "Ngram"))

ggplot(red, aes( x= cut_off, y = value, colour = variable)) + geom_line()+facet_grid(~Ngram) +
  ggtitle ("Cut off points and associated row reduction and loss of information\n by Ngram size")


crush <- data.frame(1:4, c(10,10,10,30))
x3 <- lapply(1:4, function(n) {
  filter(x3[[crush[n,1]]], Freq >=crush[n,2])
})


```


```{r}
pattern <- "all i want"
phrase <- corpus_clean(pattern)

c(paste(word(phrase, -2), "[blank]"),paste(word(phrase, -3), "[blank] [blank]"))

Ngram_case <- sapply(gregexpr("\\W+", phrase), length) + 1
words <- words[!duplicated(words[,1:Ngram_case]),1:Ngram_case]

result_blank(phrase, ngram_probs_blank)

pred_acc
```


A function designed to produce results from the blank data
```{r}
result_blank <- function(phrase, ngram_probs) { 
  phrase <- str_trim(phrase, side = "both")
  
  wordcount <- if(length(ngram_probs) < str_count(phrase, "\\S+")) {
  length(ngram_probs)
  } else  {str_count(phrase, "\\S+")}
  
  forNgrams <- sapply(1:wordcount, function(n) word(phrase, -n))
  results <-lapply(1:wordcount, function(n) filter(ngram_probs[[n]], 
                                                    predictor == forNgrams[[n]] | predictor == "[blank]"))
  results <- rbind_all(results)
  results <- ungroup(results) %>%
  arrange( desc(Prob), desc(Ngrams))
  results
  }

```


Test gap model
```{r}
y <- sapply(pred_acc$predictor, function(n) {
  
  result_test(n, x3)
})
pred_acc <- cbind(pred_acc, result_gap = do.call(rbind, y))

with(pred_acc, sum((dependent == result_gap)*Freq, na.rm = TRUE)/sum(Freq))
```

